-- Create streaming_availability_changes table
create table public.streaming_availability_changes (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  change_type text not null check (change_type in ('added', 'removed', 'leaving_soon')),
  service_id text not null,
  service_name text not null,
  previous_availability jsonb,
  current_availability jsonb,
  detected_at timestamp with time zone default timezone('utc'::text, now()) not null,
  leaving_date timestamp with time zone,
  processed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for efficient querying
create index idx_streaming_changes_tmdb_id on public.streaming_availability_changes(tmdb_id, media_type);
create index idx_streaming_changes_processed on public.streaming_availability_changes(processed);
create index idx_streaming_changes_detected_at on public.streaming_availability_changes(detected_at);
create index idx_streaming_changes_service on public.streaming_availability_changes(service_id);

-- Enable RLS
alter table public.streaming_availability_changes enable row level security;

-- Create policies - allow authenticated users to read all changes (for notification processing)
create policy "Authenticated users can view streaming changes"
  on public.streaming_availability_changes for select
  using ( auth.role() = 'authenticated' );

-- Allow service role to insert/update (for background jobs)
create policy "Service role can manage streaming changes"
  on public.streaming_availability_changes for all
  using ( auth.jwt() ->> 'role' = 'service_role' );

-- Create function to get changes for user's watchlist
create or replace function get_user_streaming_changes(user_uuid uuid)
returns table (
  id bigint,
  tmdb_id integer,
  media_type text,
  title text,
  change_type text,
  service_id text,
  service_name text,
  detected_at timestamp with time zone,
  leaving_date timestamp with time zone
) as $$
begin
  return query
  select 
    sc.id,
    sc.tmdb_id,
    sc.media_type,
    sc.title,
    sc.change_type,
    sc.service_id,
    sc.service_name,
    sc.detected_at,
    sc.leaving_date
  from streaming_availability_changes sc
  inner join watchlists w on w.tmdb_id = sc.tmdb_id and w.media_type = sc.media_type
  inner join user_preferences up on up.user_id = w.user_id
  where w.user_id = user_uuid
    and sc.processed = false
    and sc.service_id = any(up.subscribed_services)
  order by sc.detected_at desc;
end;
$$ language plpgsql security definer;

-- Create function to mark changes as processed
create or replace function mark_streaming_changes_processed(change_ids bigint[])
returns void as $$
begin
  update streaming_availability_changes 
  set processed = true 
  where id = any(change_ids);
end;
$$ language plpgsql security definer;