-- Create user_push_tokens table
create table public.user_push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  push_token text not null,
  platform text not null check (platform in ('ios', 'android', 'web')),
  device_id text,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, device_id)
);

-- Create indexes
create index idx_user_push_tokens_user_id on public.user_push_tokens(user_id);
create index idx_user_push_tokens_active on public.user_push_tokens(active);
create index idx_user_push_tokens_platform on public.user_push_tokens(platform);

-- Enable RLS
alter table public.user_push_tokens enable row level security;

-- Create policies
create policy "Users can view their own push tokens"
  on public.user_push_tokens for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own push tokens"
  on public.user_push_tokens for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own push tokens"
  on public.user_push_tokens for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own push tokens"
  on public.user_push_tokens for delete
  using ( auth.uid() = user_id );

-- Function to update updated_at timestamp
create or replace function public.update_user_push_tokens_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- Trigger to update updated_at
create trigger update_user_push_tokens_updated_at
  before update on public.user_push_tokens
  for each row execute procedure public.update_user_push_tokens_updated_at();