-- Profiles table (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Watchlist table
create table watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  status text check (status in ('plan_to_watch', 'watching', 'completed', 'dropped')),
  progress_season integer,
  progress_episode integer,
  rating integer,
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, tmdb_id, media_type)
);

-- Media Cache (Shared Streaming Availability)
create table media_cache (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  availability_data jsonb, -- Stores the JSON from TMDB/RapidAPI
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(tmdb_id, media_type)
);

-- RLS Policies (Security)
alter table profiles enable row level security;
alter table watchlists enable row level security;
alter table media_cache enable row level security;

-- Profiles: Users can read/update their own
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Watchlists: Users can only see/edit their own
create policy "Users can see own watchlist." on watchlists for select using (auth.uid() = user_id);
create policy "Users can insert own watchlist." on watchlists for insert with check (auth.uid() = user_id);
create policy "Users can update own watchlist." on watchlists for update using (auth.uid() = user_id);
create policy "Users can delete own watchlist." on watchlists for delete using (auth.uid() = user_id);

-- Media Cache: Readable by everyone, Insert/Update by authenticated users (when they fetch new data)
create policy "Cache is viewable by everyone." on media_cache for select using (true);
create policy "Authenticated users can update cache." on media_cache for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update cache rows." on media_cache for update using (auth.role() = 'authenticated');

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Recommendations table (Persist monthly recommendations)
create table recommendations (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  month text not null,
  year integer not null,
  data jsonb not null, -- Stores the MonthlyRecommendation object
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, month, year)
);

-- Recommendations: Users can only see/edit their own
alter table recommendations enable row level security;
create policy "Users can see own recommendations." on recommendations for select using (auth.uid() = user_id);
create policy "Users can insert own recommendations." on recommendations for insert with check (auth.uid() = user_id);
create policy "Users can update own recommendations." on recommendations for update using (auth.uid() = user_id);
create policy "Users can delete own recommendations." on recommendations for delete using (auth.uid() = user_id);
